import React from 'react';
import Link from 'next/link';
import { Shield, Lock, EyeOff, Server, Globe, FileText, ArrowLeft } from 'lucide-react';
import { SubHeader } from '../../components/SubHeader';
import { Footer } from '../../components/Footer';

export const metadata = {
  title: 'Privacy Policy — SajiloAlert',
  description: 'Privacy Policy and data practices for the SajiloAlert open-source library and documentation portal.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-sans pt-16">
      <SubHeader currentPageTitle="Privacy Policy" />

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-8 py-10">
        {/* Breadcrumb */}
        <div className="mb-6 flex items-center gap-2 text-xs font-semibold text-slate-500">
          <Link href="/" className="hover:text-slate-900 transition">Home</Link>
          <span>/</span>
          <span className="text-[#DC143C]">Privacy Policy</span>
        </div>

        {/* Hero title */}
        <div className="bg-white rounded-2xl p-6 sm:p-10 border border-slate-200 shadow-xs mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2.5 rounded-xl bg-red-50 text-[#DC143C] border border-red-100">
              <Shield className="w-6 h-6" />
            </div>
            <div>
              <span className="text-xs font-bold text-[#DC143C] uppercase tracking-wider">Legal & Compliance</span>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">Privacy Policy</h1>
            </div>
          </div>
          <p className="text-sm sm:text-base text-slate-600 leading-relaxed">
            Effective Date: August 16, 2026. This Privacy Policy details how SajiloAlert (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;the library&rdquo;) handles information when you use our npm package and visit this documentation portal.
          </p>
          <div className="mt-4 pt-4 border-t border-slate-100 flex flex-wrap items-center gap-4 text-xs font-medium text-slate-500">
            <span>Last Updated: August 2026</span>
            <span>•</span>
            <span>Version: 1.0.0</span>
            <span>•</span>
            <span className="text-emerald-700 font-semibold">100% Client-Side / Zero Telemetry</span>
          </div>
        </div>

        {/* Content sections */}
        <div className="space-y-6">
          {/* Section 1: Zero Data Collection */}
          <div className="bg-white rounded-xl p-6 sm:p-8 border border-slate-200 shadow-2xs">
            <div className="flex items-center gap-2.5 mb-3">
              <EyeOff className="w-5 h-5 text-[#003893]" />
              <h2 className="text-lg font-bold text-slate-900">1. Zero Data Collection & Telemetry</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed mb-3">
              <strong>SajiloAlert is a pure client-side UI notification library.</strong> It runs entirely inside your end-user&rsquo;s browser environment or JavaScript runtime.
            </p>
            <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 ml-2">
              <li>We do <strong>NOT</strong> collect, store, transmit, or monetize any personal user data.</li>
              <li>We do <strong>NOT</strong> bundle any analytics trackers, diagnostic telemetry, or tracking pixels inside the npm package.</li>
              <li>Alert messages, input values in confirmation dialogs, and toast payloads remain strictly inside your application memory.</li>
            </ul>
          </div>

          {/* Section 2: Documentation Portal */}
          <div className="bg-white rounded-xl p-6 sm:p-8 border border-slate-200 shadow-2xs">
            <div className="flex items-center gap-2.5 mb-3">
              <Server className="w-5 h-5 text-indigo-600" />
              <h2 className="text-lg font-bold text-slate-900">2. Documentation Website & Hosting</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed mb-3">
              When accessing this interactive documentation portal:
            </p>
            <ul className="list-disc list-inside space-y-2 text-sm text-slate-600 ml-2">
              <li>Standard web server access logs (such as IP addresses, browser user agent, and request timestamps) may be generated by the cloud hosting infrastructure solely for security, DDoS prevention, and service availability.</li>
              <li>Interactive preferences (such as selected language or playground theme) are stored purely in transient client state and are not transmitted to external advertising networks.</li>
            </ul>
          </div>

          {/* Section 3: Third-Party Dependencies */}
          <div className="bg-white rounded-xl p-6 sm:p-8 border border-slate-200 shadow-2xs">
            <div className="flex items-center gap-2.5 mb-3">
              <Lock className="w-5 h-5 text-emerald-600" />
              <h2 className="text-lg font-bold text-slate-900">3. Zero Third-Party Dependencies</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              The core SajiloAlert package is built with <strong>zero runtime dependencies</strong>. This ensures that no hidden third-party scripts, malicious packages, or unauthorized data pipelines are introduced into your production software supply chain.
            </p>
          </div>

          {/* Section 4: Contact Information */}
          <div className="bg-white rounded-xl p-6 sm:p-8 border border-slate-200 shadow-2xs">
            <div className="flex items-center gap-2.5 mb-3">
              <FileText className="w-5 h-5 text-amber-600" />
              <h2 className="text-lg font-bold text-slate-900">4. Privacy Inquiries</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              If you have any questions or security concerns regarding this Privacy Policy or the SajiloAlert open-source project, please reach out to:
            </p>
            <div className="mt-3 p-4 rounded-lg bg-slate-50 border border-slate-200 font-mono text-xs sm:text-sm text-slate-800">
              <p>Maintainer: Ankit Khatri KC</p>
              <p>Email: <a href="mailto:ankitkhatrik6@gmail.com" className="text-[#003893] hover:underline font-semibold">ankitkhatrik6@gmail.com</a></p>
            </div>
          </div>
        </div>

        {/* Back navigation */}
        <div className="mt-8 text-center">
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 hover:text-slate-900 font-semibold text-xs sm:text-sm shadow-2xs transition"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Return to SajiloAlert Documentation</span>
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
